# Generated by Django 5.2.8 on 2025-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("email", models.TextField(unique=True)),
                ("enrollment_date", models.DateField()),
            ],
        ),
    ]
