# Generated by Django 5.2.8 on 2025-11-09 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""INSERT INTO students_student (first_name, last_name, email, enrollment_date) VALUES
                ('John', 'Doe', 'john.doe@example.com', '2023-09-01'),
                ('Jane', 'Smith', 'jane.smith@example.com', '2023-09-01'),
                ('Jim', 'Beam', 'jim.beam@example.com', '2023-09-02');
            """,
            reverse_sql="""
                TRUNCATE TABLE students_student RESTART IDENTITY CASCADE;
            """,
        ),
    ]
