# Generated by Django 5.2.8 on 2025-11-10 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="students",
        ),
    ]
